export const orgTree = {
  id: 1,
  name: "Alice Johnson",
  position: "CEO",
  department: "Executive",
  contact: "123-456-7890",
  email: "alice.johnson@example.com",
  image: "https://i.pravatar.cc/150?img=1",
  children: [
    {
      id: 2,
      name: "Bob Smith",
      position: "CTO",
      department: "Technology",
      contact: "234-567-8901",
      email: "bob.smith@example.com",
      image: "https://i.pravatar.cc/150?img=2",
      children: [
        {
          id: 3,
          name: "Charlie Davis",
          position: "Engineering Manager",
          department: "Engineering",
          contact: "345-678-9012",
          email: "charlie.davis@example.com",
          image: "https://i.pravatar.cc/150?img=3",
          children: [
            {
              id: 4,
              name: "David White",
              position: "Software Engineer",
              department: "Engineering",
              contact: "456-789-0123",
              email: "david.white@example.com",
              image: "https://i.pravatar.cc/150?img=4",
              children: [],
            },
            {
              id: 5,
              name: "Eve Brown",
              position: "Software Engineer",
              department: "Engineering",
              contact: "567-890-1234",
              email: "eve.brown@example.com",
              image: "https://i.pravatar.cc/150?img=5",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 6,
      name: "Sophia Green",
      position: "CFO",
      department: "Finance",
      contact: "678-901-2345",
      email: "sophia.green@example.com",
      image: "https://i.pravatar.cc/150?img=6",
      children: [
        {
          id: 7,
          name: "Liam Black",
          position: "Finance Manager",
          department: "Finance",
          contact: "789-012-3456",
          email: "liam.black@example.com",
          image: "https://i.pravatar.cc/150?img=7",
          children: [
            {
              id: 8,
              name: "Emma Wilson",
              position: "Accountant",
              department: "Finance",
              contact: "890-123-4567",
              email: "emma.wilson@example.com",
              image: "https://i.pravatar.cc/150?img=8",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 9,
      name: "Michael King",
      position: "COO",
      department: "Operations",
      contact: "901-234-5678",
      email: "michael.king@example.com",
      image: "https://i.pravatar.cc/150?img=9",
      children: [
        {
          id: 10,
          name: "Olivia Taylor",
          position: "Operations Manager",
          department: "Operations",
          contact: "012-345-6789",
          email: "olivia.taylor@example.com",
          image: "https://i.pravatar.cc/150?img=10",
          children: [
            {
              id: 11,
              name: "Noah Harris",
              position: "Logistics Coordinator",
              department: "Operations",
              contact: "123-543-7690",
              email: "noah.harris@example.com",
              image: "https://i.pravatar.cc/150?img=11",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};
