export const orgTree = {
  id: 1,
  name: "Alice Johnson",
  position: "CEO",
  department: "Executive",
  contact: "123-456-7890",
  email: "alice.johnson@example.com",
  image: "https://i.pravatar.cc/150?img=1",
  children: [
    {
      id: 2,
      name: "Bob Smith",
      position: "CTO",
      department: "Technology",
      contact: "234-567-8901",
      email: "bob.smith@example.com",
      image: "https://i.pravatar.cc/150?img=2",
      children: [
        {
          id: 3,
          name: "Charlie Davis",
          position: "Engineering Manager",
          department: "Engineering",
          contact: "345-678-9012",
          email: "charlie.davis@example.com",
          image: "https://i.pravatar.cc/150?img=3",
          children: [
            {
              id: 4,
              name: "David White",
              position: "Software Engineer",
              department: "Engineering",
              contact: "456-789-0123",
              email: "david.white@example.com",
              image: "https://i.pravatar.cc/150?img=4",
              children: [],
            },
            {
              id: 5,
              name: "Eve Brown",
              position: "Software Engineer",
              department: "Engineering",
              contact: "567-890-1234",
              email: "eve.brown@example.com",
              image: "https://i.pravatar.cc/150?img=5",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 6,
      name: "Sophia Green",
      position: "CFO",
      department: "Finance",
      contact: "678-901-2345",
      email: "sophia.green@example.com",
      image: "https://i.pravatar.cc/150?img=6",
      children: [
        {
          id: 7,
          name: "Liam Black",
          position: "Finance Manager",
          department: "Finance",
          contact: "789-012-3456",
          email: "liam.black@example.com",
          image: "https://i.pravatar.cc/150?img=7",
          children: [
            {
              id: 8,
              name: "Emma Wilson",
              position: "Accountant",
              department: "Finance",
              contact: "890-123-4567",
              email: "emma.wilson@example.com",
              image: "https://i.pravatar.cc/150?img=8",
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 9,
      name: "Michael King",
      position: "COO",
      department: "Operations",
      contact: "901-234-5678",
      email: "michael.king@example.com",
      image: "https://i.pravatar.cc/150?img=9",
      children: [
        {
          id: 10,
          name: "Olivia Taylor",
          position: "Operations Manager",
          department: "Operations",
          contact: "012-345-6789",
          email: "olivia.taylor@example.com",
          image: "https://i.pravatar.cc/150?img=10",
          children: [
            {
              id: 11,
              name: "Noah Harris",
              position: "Logistics Coordinator",
              department: "Operations",
              contact: "123-543-7690",
              email: "noah.harris@example.com",
              image: "https://i.pravatar.cc/150?img=11",
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export const email: EmailType[] = [
  {
    id: 1,
    title: "Leave Request",
    createdAt: new Date("2025-03-01T08:45:00"),
    createdBy: "Michael King",
    status: "approved",
    approvedBy: "Super Admin",
    content: "Due to sickness",
    comment: "",
    requestFor: "Leave",
    read: true,
  },
  {
    id: 2,
    title: "Asset Request",
    createdAt: new Date("2025-02-28T10:30:00"),
    createdBy: "Michael King",
    status: null,
    approvedBy: null,
    content: "Need a laptop for project work",
    comment: "",
    requestFor: "Lenovo-Laptop",
    read: false,
  },
  {
    id: 3,
    title: "Budget Approval",
    createdAt: new Date("2025-03-05T14:20:00"),
    createdBy: "Sarah Johnson",
    status: "rejected",
    approvedBy: "Finance Admin",
    content: "Requesting approval for a team lunch budget.",
    comment: "Exceeds budget limits.",
    requestFor: "Budget",
    read: true,
  },
  {
    id: 4,
    title: "Leave Request",
    createdAt: new Date("2025-02-15T09:15:00"),
    createdBy: "John Doe",
    status: "approved",
    approvedBy: "HR Admin",
    content: "Requesting leave for personal reasons.",
    comment: "Approved for 3 days.",
    requestFor: "Leave",
    read: true,
  },
  {
    id: 5,
    title: "Project Approval",
    createdAt: new Date("2025-03-03T11:50:00"),
    createdBy: "Alice Brown",
    status: null,
    approvedBy: null,
    content: "Proposal for the Q2 Marketing Campaign.",
    comment: "",
    requestFor: "Project",
    read: false,
  },
  {
    id: 6,
    title: "Access Request",
    createdAt: new Date("2025-03-04T16:40:00"),
    createdBy: "David Lee",
    status: "approved",
    approvedBy: "IT Admin",
    content: "Requesting access to the analytics dashboard.",
    comment: "",
    requestFor: "Access",
    read: true,
  },
  {
    id: 7,
    title: "Conference Room Booking",
    createdAt: new Date("2025-02-20T14:05:00"),
    createdBy: "Jane Cooper",
    status: null,
    approvedBy: null,
    content: "Booking a conference room for the quarterly meeting.",
    comment: "",
    requestFor: "Booking",
    read: false,
  },
  {
    id: 8,
    title: "Policy Update Request",
    createdAt: new Date("2025-02-25T12:30:00"),
    createdBy: "Chris Evans",
    status: "rejected",
    approvedBy: "HR Admin",
    content: "Request to update work-from-home policy.",
    comment: "Needs further discussion.",
    requestFor: "Policy Update",
    read: true,
  },
  {
    id: 9,
    title: "Training Request",
    createdAt: new Date("2025-02-10T10:00:00"),
    createdBy: "Emma Watson",
    status: "approved",
    approvedBy: "Training Coordinator",
    content: "Request to enroll in React Advanced Training.",
    comment: "Training scheduled for March 15th.",
    requestFor: "Training",
    read: true,
  },
  {
    id: 10,
    title: "Laptop Repair",
    createdAt: new Date("2025-03-02T13:45:00"),
    createdBy: "James Bond",
    status: null,
    approvedBy: null,
    content: "Laptop malfunctioning, requesting repairs.",
    comment: "",
    requestFor: "Repair",
    read: false,
  },
  {
    id: 11,
    title: "Team Lunch Request",
    createdAt: new Date("2025-02-28T15:30:00"),
    createdBy: "Anna Taylor",
    status: "approved",
    approvedBy: "Manager",
    content: "Requesting approval for a team lunch expense.",
    comment: "Approved within budget.",
    requestFor: "Lunch",
    read: true,
  },
  {
    id: 12,
    title: "Workstation Setup",
    createdAt: new Date("2025-03-01T09:25:00"),
    createdBy: "Sam Wilson",
    status: null,
    approvedBy: null,
    content: "Requesting a new workstation for a new joiner.",
    comment: "",
    requestFor: "Setup",
    read: false,
  },
];
